version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: vkpvp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
      dockerfile: ../docker/client.Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./client/dist:/usr/share/nginx/html:ro

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - client
      - backend

volumes:
  pgdata: